#!/bin/sh

#  executor.sh
#  StarTroupial
#
#  Created by Jenny Valdez on 08/11/12.
#  Copyright (c) 2012 Jenny Valdez. All rights reserved.

if gcc testOpenAL.h -Wall
then
    echo '#define USE_SOUNDS true' > config.h
else
    echo '' > config.h
fi

make
./playGame