#!/bin/sh

#  executor.sh
#  StarTroupial
#
#  Created by Jenny Valdez on 08/11/12.
#  Copyright (c) 2012 Jenny Valdez. All rights reserved.

if gcc testOpenAL.h
then
    echo '#define USE_SOUNDS true' > config.h
    echo 'Using sounds...'
    make MUSIC="m"
else
    echo '' > config.h
    echo 'NOT using sounds...'
    make
fi

./playGame